version: "3.9"
services:
  db:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build: .
    environment:
      - POSTGRES_HOST=db
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:5000
    depends_on:
      - db
volumes:
  postgres_data: